### ISSUE TITLE
Editing an item will duplicate it, one has the old name and the other one the new name

### ISSUE THREAD

**Issue by johannesmols** [ludvigbruchmann/P3-Server#4]

**Comment by johannesmols** [comment]
could also be a client error. i just know that that's what shows up in the app after editing an item

**Comment by alexampersandria** [comment]
This is caused by editing the _id field, the _id field is a unique id number per entry generated by neDB, we use the to reference the entry in other tables.

Issue caused by f763daa

**Comment by borisyordanov** [comment]
@ludvigbruchmann what do you mean by editing the _id field?

**Comment by alexampersandria** [comment]
In the referenced commit you update the _id field, hard to add code snippets on mobile but it's line 171

**Comment by borisyordanov** [comment]
isn't the first argument in the update method (the one on line 171), the search query? The second object that you pass is what gets actually updated

https://github.com/louischatriot/nedb#updating-documents

**Comment by alexampersandria** [comment]
Oh yeah you're right, then I have no idea what causes it, @johannesmols can you dump your db file before and after you edit an item

**Comment by alexampersandria** [comment]
I can conclude now that there are no duplicates in the databse, it is expected behavior from neDB, I am not sure how you are getting duplicates, but if you use the /api/tags endpoint you can see that there are not duplicates.

See [neDB: Upserting keeps adding duplicates of the same record to the database](https://github.com/louischatriot/nedb/issues/226).
